### ISSUE TITLE
Surfacing widget doesn't turn spindle on w/ IOT Relay

### ISSUE THREAD

**Issue by brrian11** [OpenBuilds/OpenBuilds-CONTROL#125]
I'm using an IOT Relay to automatically start & stop my spindle, as shown here:

https://docs.openbuilds.com/blackbox/#331-dewalt611iot.html

When using the CONTROL surfacing widget, the spindle does not start.

**Comment by petervanderwalt** [comment]
Since V1.0.180 already it included a M3S1000: See https://github.com/OpenBuilds/OpenBuilds-CONTROL/blob/5c3675ff8460dbdc6155a3c1e145263de3c47c12/app/wizards/surfacing.js#L70 

Something in your own setup? 
Check the GCODE editor tab after creating the surfacing toolpath, you'll see the M3S1000 is present to turn on the Spindle
