### ISSUE TITLE
Finish Modal parser

### ISSUE THREAD

**Issue by petervanderwalt** [OpenBuilds/OpenBuilds-CONTROL#240]
https://github.com/OpenBuilds/OpenBuilds-CONTROL/blob/master/index.js#L2506-L2508 to be extended for all other modals as needed for one of  @sharmstr 's projects

**Comment by petervanderwalt** [comment]
v1.0.314 has a couple more modal statusses available 

![image](https://user-images.githubusercontent.com/31449271/160621704-a6114c62-cc03-47dc-9834-58fddcb71d11.png)

**Comment by sharmstr** [comment]
Thank you for this.  Quick question though.  I was testing and issued a "g20" (notice lowercase g) and thought it didnt work.  The problem is that it doesnt switch units if you use a lowercase g instead of an uppercase G.  Is this a grbl thing or a Control issue?

[10:25:16] [ g20 ] ok  // notice that grbl only responds with ok, not a section line with current modals

[10:25:28] [ G20 ] ok

[10:25:28] [ $G ] [GC:G0 G54 G17 G20 G90 G94 M5 M9 T0 F0 S0]

**Comment by petervanderwalt** [comment]
That might be us.  
Send a lowercase g20 and then manually a $G - to see if Grbl took it?

**Comment by sharmstr** [comment]
Yep.  grbl accepts it.  All of my code uses capitals in gcode so its not a big deal, but you might want to sort that out eventually.  :)

**Comment by sharmstr** [comment]
Ok.  So if I issue a g20, I believe grbl accepts it.  I dont know until I then issue a $G to check.   The only reason I say this is because if I issue a g20 and check laststatus, it will still say G21.  BUT if I then issue a $G, then laststatus will update and correctly show G20.

**Comment by petervanderwalt** [comment]
Cool then - fix incoming soon (check for modal commands regardless of case, to send $G after)

**Comment by petervanderwalt** [comment]
![image](https://user-images.githubusercontent.com/31449271/164086162-f48e03c1-7bf3-437a-a661-fb9da7a8afdc.png)
V1.0.318 or later - out soon (:
