### ISSUE TITLE
segfault on raspbian buster

### ISSUE THREAD

**Issue by ghost** [OpenBuilds/OpenBuilds-CONTROL#91]
related: https://github.com/OpenBuilds/OpenBuilds-CONTROL/issues/86

raspbian buster uses libc6 2.28 by default which causes segfault. OpenBuilds-CONTROL needs **exactly** 2.27

I would just recommend using the no-compile version
https://github.com/OpenBuilds/OpenBuilds-CONTROL/wiki/Run-on-a-Raspberry-Pi-(No-Compile-Method)
Albeit that document needs to be updated with a 
`sudo apt-get install -y npm` in section 3 and `npm rebuild` in section 5

**Comment by openbuilds-engineer** [comment]
https://github.com/electron/electron/issues/16205#issuecomment-508454921 mentions SNAP builds work, havent had time to play with that. Any volunteers? (; 

Will need to add all the Snapcraft dependencies etc, manual here https://www.electron.build/configuration/snap

Something like https://github.com/OpenBuilds/OpenBuilds-CONTROL/wiki/Compiling-on-Raspberry-Pi-%5Bunofficial%5D but at step 6 instead of ```./node_modules/.bin/build --armv7l --linux tar.xz ``` do a SNAP build

**Comment by petervanderwalt** [comment]
Closing: Refer https://github.com/OpenBuilds/OpenBuilds-CONTROL/wiki/Run-on-a-Raspberry-Pi-(No-Compile-Method)
